### ISSUE TITLE
Vagrant deployment fails

### ISSUE THREAD

**Issue by atsag** [apache/openwhisk#4436]
## Environment details:

* Vagrant 2.2.0 deployment on Windows 10

## Steps to reproduce the issue:

1.   Clone the incubator-openwhisk repository using the command provided in the tools/vagrant/README.md file
2.   Follow the instructions for a local CouchDB deployment executing the `hello` script

## Provide the expected results and outputs:

A successful Vagrant deployment

## Provide the actual results and outputs:

The Vagrant deployment is terminated as unsuccessful. The execution trace of the last playbook (routemgmt.yml) is provided below 
```
default: ++ su vagrant -c 'ansible-playbook -i environments/vagrant routemgmt.yml'
    default:
    default: PLAY [ansible] *****************************************************************
    default:  [WARNING]: While constructing a mapping from
    default: /home/vagrant/openwhisk/ansible/environments/vagrant/group_vars/all, line 4,
    default: column 1, found a duplicate dict key (invoker_use_runc). Using last defined
    default: value only.
    default:
    default: TASK [Gathering Facts] *********************************************************
    default: Tuesday 09 April 2019  14:36:18 +0000 (0:00:00.340)       0:00:00.340 *********
    default: ok: [ansible]
    default:
    default: TASK [routemgmt : install route management actions] ****************************
    default: Tuesday 09 April 2019  14:36:20 +0000 (0:00:01.985)       0:00:02.326 *********
    default: fatal: [ansible]: FAILED! => {"changed": true, "cmd": "./installRouteMgmt.sh /home/vagrant/openwhisk/ansible/files/auth.whisk.system 172.17.0.1 /whisk.system /home/vagrant/openwhisk/bin/wsk", "delta": "0:00:00.493131", "end": "2019-04-09 14:36:21.481893", "msg": "non-zero return code", "rc": 127, "start": "2019-04-09 14:36:20.988762", "stderr": "./installRouteMgmt.sh: line 61: npm: command not found", "stderr_lines": ["./installRouteMgmt.sh: line 61: npm: command not found"], "stdout": "Installing apimgmt package\nok: updated package apimgmt\nCreating NPM module .zip files", "stdout_lines": ["Installing apimgmt package", "ok: updated package apimgmt", "Creating NPM module .zip files"]}
    default:
    default: [FAILED]
    default: > ./installRouteMgmt.sh /home/vagrant/openwhisk/ansible/files/auth.whisk.system 172.17.0.1 /whisk.system /home/vagrant/openwhisk/bin/wsk
    default: non-zero return code
    default: Installing apimgmt package ok: updated package apimgmt Creating NPM module .zip
    default: files
    default: ./installRouteMgmt.sh: line 61: npm: command not found
    default:
    default: PLAY RECAP *********************************************************************
    default: ansible                    : ok=1    changed=0    unreachable=0    failed=1
    default: Tuesday 09 April 2019  14:36:21 +0000 (0:00:01.160)       0:00:03.486 *********
    default: ===============================================================================
    default: Gathering Facts --------------------------------------------------------- 1.99s
    default: routemgmt : install route management actions ---------------------------- 1.16s
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Additional information you deem important:
The solution to this problem seems to be installing the npm package on the Ubuntu host, by suitably modifying the Vagrantfile.
