### ISSUE TITLE
Kafka container doesn't have a volume mapping for persisting data

### ISSUE THREAD

**Issue by upgle** [apache/openwhisk#4676]
There is no volume mapping for persisting Kafka data. Although unlikely, it can cause data loss.

If there's no reason not to use the volume mapping, can I add it? 

```yaml
  docker_container:
    name: kafka{{ groups['kafkas'].index(inventory_hostname) }}
    image: "{{ kafka_image }}"
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    env: "{{ kafka_env_vars }}"
    ports: "{{ ports_to_expose }}"
    volumes:
      - "{{ config_root_dir }}/kafka/certs:/config"
    pull: true
```
