### ISSUE TITLE
Increase Container Pool Size: Invoker userMemory or ContainerPool userMemory?

### ISSUE THREAD

**Issue by zzhou612** [apache/openwhisk#4912]
## Environment details:

* Ubuntu 18.04

## Provide the expected results and outputs:

I am trying to increase the user memory of the container pool to allow more containers to run concurrently. I notice that there are two configurable parameters: invoker user memory and container pool user memory.

`openwhisk/ansible/group_vars/all`
```
invoker:
  dir:
    become: "{{ invoker_dir_become | default(false) }}"
  confdir: "{{ config_root_dir }}/invoker"
  port: 12001
  heap: "{{ invoker_heap | default('2g') }}"
  arguments: "{{ invoker_arguments | default('') }}"
  userMemory: "{{ invoker_user_memory | default('2048m') }}"
```
`openwhisk/core/invoker/src/main/resources/application.conf`
```
  container-pool {
    user-memory: 1024 m
    concurrent-peek-factor: 0.5 #factor used to limit message peeking: 0 < factor <= 1.0 - larger number improves concurrent processing, but increases risk of message loss during invoker crash
    akka-client:  false # if true, use PoolingContainerClient for HTTP from invoker to action container (otherwise use ApacheBlockingContainerClient)
  }
```

Currently, I am using the docker-compose deployment method. And there are similar parameters in the env file.

`openwhisk-devtools/docker-compose/docker-whisk-controller.env`
```
CONFIG_whisk_loadbalancer_invokerUserMemory=1024m
CONFIG_whisk_containerPool_userMemory=1024m
```

After increasing `CONFIG_whisk_containerPool_userMemory`, more containers could run concurrently, avoiding cold starts. But I am wondering what is the invoker user memory? I looked through the source code and found that most of the configurations are read from the container pool config.

I checked the previous issues https://github.com/apache/openwhisk/issues/4526, https://github.com/apache/openwhisk/issues/4414. They were modifying `invoker_user_memory` to increase the container pool size. But I checked the source code, and it seems that even the InvokerInstanceId's user memory is decided by the container pool config.
