### ISSUE TITLE
helm install fails on local k8s

### ISSUE THREAD

**Issue by Peperud** [apache/openwhisk#5498]
## Environment details:
Local k8s cluster on Linux

## Steps to reproduce the issue:
Followed the instructions to install local with ```helm```
```mycluster.yaml``` used:
```
whisk:
  ingress:
    type: NodePort
    apiHostName: localhost
    apiHostPort: 31001
    useInternally: false

nginx:
  httpsNodePort: 31001

# A single node cluster; so disable affinity
affinity:
  enabled: false
toleration:
  enabled: false
invoker:
  options: "-Dwhisk.kubernetes.user-pod-node-affinity.enabled=false"
  containerFactory:
    impl: "kubernetes"
```

## Provide the actual results and outputs:
```
NAME                                     READY   STATUS      RESTARTS      AGE
owdev-alarmprovider-6bf4cdd68c-sbnpf     1/1     Running     2 (29m ago)   28h
owdev-apigateway-644688857f-gj55k        1/1     Running     2 (29m ago)   28h
owdev-controller-0                       1/1     Running     2 (29m ago)   28h
owdev-couchdb-555b6d8ff4-xbjh7           1/1     Running     2 (29m ago)   28h
owdev-gen-certs-zbzqh                    0/1     Completed   0             28h
owdev-init-couchdb-7gx6f                 0/1     Completed   0             28h
owdev-install-packages-f84xt             0/1     Error       0             28h
owdev-install-packages-qlmdt             0/1     Error       0             28h
owdev-install-packages-qqlzr             0/1     Error       0             25h
owdev-install-packages-ttk2m             0/1     Unknown     0             28h
owdev-invoker-0                          1/1     Running     2 (29m ago)   28h
owdev-kafka-0                            1/1     Running     2 (29m ago)   28h
owdev-kafkaprovider-5785cbb579-6wgq4     1/1     Running     2 (29m ago)   28h
owdev-nginx-6c7448668b-vthv2             1/1     Running     2 (29m ago)   28h
owdev-redis-848f56f555-qzbpx             1/1     Running     2 (29m ago)   28h
owdev-tests-package-checker              0/1     Error       0             7m28s
owdev-wskadmin                           1/1     Running     2 (29m ago)   28h
owdev-zookeeper-0                        1/1     Running     2 (29m ago)   28h
wskowdev-invoker-00-1-prewarm-nodejs10   1/1     Running     0             27m
wskowdev-invoker-00-2-prewarm-nodejs10   1/1     Running     0             27m
```
```owdev-install-packages-*``` all failed.
Logs from the pods look like this:
```
Defaulted container "install-packages" out of: install-packages, wait-for-healthy-invoker (init)
Error from server: Get "https://192.168.13.69:10250/containerLogs/openwhisk/owdev-install-packages-ttk2m/install-packages": tls: failed to verify certificate: x509: certificate is valid for 192.168.13.68, 192.168.110.1, 192.168.39.1, 192.168.122.1, 172.18.0.1, 172.17.0.1, 172.28.0.1, not 192.168.13.69
```

Looks like a wrong certificate was generated and set during install?
