### ISSUE TITLE
How to set a custom certificate for the helm install?

### ISSUE THREAD

**Issue by Peperud** [apache/openwhisk#5499]
There is this:
```yaml
whisk:
  # Ingress defines how to access OpenWhisk from outside the Kubernetes cluster.
  # Only a subset of the values are actually used on any specific type of cluster.
  # See the "Configuring OpenWhisk section" of the docs/k8s-*.md that matches
  # your cluster type for details on what values to provide and how to get them.
  ingress:
    awsSSL: "false"
    apiHostName: ""
    apiHostPort: 31001
    apiHostProto: "https"
    type: NodePort
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    domain: "domain"
    tls:
      enabled: false
      secretenabled: false
      createsecret: false
      secretname: "ow-ingress-tls-secret"
      secrettype: "type"
      crt: "crt"
      key: "key"
```
I have generated my own certificate. 
But no matter what I set ```crt``` ,```key``` and ```enabled``` to, I still end up with the dreaded ```*.localhost"```.
